

// import "./globals.css";
// import { Inter } from "next/font/google";
// import AuthProvider from "./context/AuthProvider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "หน้าหลัก",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <AuthProvider>{children}</AuthProvider>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "./context/AuthProvider";
import Chatbot from "@/components/Chatbot"; // 👈 import chatbot

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "หน้าหลัก",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <Chatbot /> {/* 👈 เพิ่ม chatbot ตรงนี้ */}
        </AuthProvider>
      </body>
    </html>
  );
}
