import type { Metadata } from 'next'
import { IBM_Plex_Sans_Thai } from 'next/font/google'

const ibmPlexThai = IBM_Plex_Sans_Thai({ subsets: ['thai', 'latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'เข้าสู่ระบบ...',
  description: 'Generated by create next app',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="th">
      <body className={ibmPlexThai.className}>{children}</body>
    </html>
  )
}
